name: bebunge
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  advanced_in_app_review: ^1.1.3
  app_version_update: ^3.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  dropdown_search: ^5.0.6
  easy_debounce: ^2.0.3
  easy_localization: ^3.0.2
  easy_stepper: ^0.5.2+1
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_downloader: ^1.11.4
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0-alpha.6
  flutter_image_compress: ^2.0.4
  flutter_inappwebview: ^6.0.0-beta.22
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.2
  flutter_widget_from_html_core: ^0.10.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.8
  http: ^0.13.6
  http_interceptor: ^1.0.2
  image_picker: ^1.0.2
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  intl_utils: ^2.8.1
  json_annotation: ^4.8.0
  localization: ^2.1.0
  logger: ^1.2.2
  lottie: ^2.3.2
  material_symbols_icons: ^4.39.5
  modal_bottom_sheet: ^3.0.0-pre
  money2: ^3.3.0
  multi_image_picker_view: ^0.0.17
  package_info_plus: ^3.0.3
  page_transition: ^2.0.9
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  pinput: ^3.0.1
  ripple_wave: ^0.0.2
  search_page: ^2.3.0
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_datepicker: ^20.3.59
  textfield_tags: ^2.0.2
  url_launcher: ^6.1.10
  wakelock: ^0.6.2
  zoom_tap_animation: ^1.1.0
targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: true
          explicit_to_json: false

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.6.1

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/l10n/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
